// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdE3r7emokK4jo9LW2PnLior_vun-qmtI',
    appId: '1:68328845844:web:e8cc23b6246bed74176d01',
    messagingSenderId: '68328845844',
    projectId: 'flutterclinicapp-77e7a',
    authDomain: 'flutterclinicapp-77e7a.firebaseapp.com',
    storageBucket: 'flutterclinicapp-77e7a.firebasestorage.app',
    measurementId: 'G-QZ5EPTPX3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVHVI1XwK-ciNKxJ8mzZKFMdtdV2tjQUU',
    appId: '1:68328845844:android:c7574ea38d89f7f9176d01',
    messagingSenderId: '68328845844',
    projectId: 'flutterclinicapp-77e7a',
    storageBucket: 'flutterclinicapp-77e7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1xyJZOEc6i2o5G0aP5ypOdgVsC5u0xrQ',
    appId: '1:68328845844:ios:7f163e2bf7fc7266176d01',
    messagingSenderId: '68328845844',
    projectId: 'flutterclinicapp-77e7a',
    storageBucket: 'flutterclinicapp-77e7a.firebasestorage.app',
    iosBundleId: 'com.clinicapp.clinicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1xyJZOEc6i2o5G0aP5ypOdgVsC5u0xrQ',
    appId: '1:68328845844:ios:7f163e2bf7fc7266176d01',
    messagingSenderId: '68328845844',
    projectId: 'flutterclinicapp-77e7a',
    storageBucket: 'flutterclinicapp-77e7a.firebasestorage.app',
    iosBundleId: 'com.clinicapp.clinicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdE3r7emokK4jo9LW2PnLior_vun-qmtI',
    appId: '1:68328845844:web:2201a81fb5d00307176d01',
    messagingSenderId: '68328845844',
    projectId: 'flutterclinicapp-77e7a',
    authDomain: 'flutterclinicapp-77e7a.firebaseapp.com',
    storageBucket: 'flutterclinicapp-77e7a.firebasestorage.app',
    measurementId: 'G-0N2QR8YYNX',
  );

}